FleetManagment/FleetManagement.Web2/Controllers/EJobController.cs
using FleetManagement.Web2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FleetManagement.Web2.Controllers
{
    public class EJobController : Controller
    {
        // GET: EJob
        ClientHelper ch = new ClientHelper();
        public ActionResult Job()
        {
            return View("Job");
        }
        public string GetJobListInfo()
        {
            var trucks = ch.RetrieveTrucks();
            var users = ch.RetrieveInfo();
            var job = ch.RetrieveJobs();
            List<Job> truck = new List<Job>();
            foreach (var j in job)
            {
                bool a = true;
                foreach (var u in users)
                {
                    foreach (var i in trucks)
                    {
                        if (a)
                        {
                            if ((j.UserName.Equals(u.UserName)) && (j.UserName.Equals(i.UserName)))
                            {

                                if (j.Active)
                                {
                                    if (i.UserName.Equals("No Driver"))
                                    {
                                        truck.Add(new Web2.Job() { JobId = j.JobId, UserName = j.UserName, FirstName = "Needs", LastName = "Driver", SLat = j.SLat, SLon = j.SLon, ELat = j.ELat, ELon = j.ELon, Active = j.Active, Color = "table-danger" });
                                        a = false;
                                    }else
                                    {
                                        truck.Add(new Web2.Job() { JobId = j.JobId, UserName = j.UserName, FirstName = u.FirstName, LastName = u.LastName, SLat = j.SLat, SLon = j.SLon, ELat = j.ELat, ELon = j.ELon, Active = j.Active, Color = "table-info" });
                                        a = false;
                                    }
                                }
                                else
                                {
                                    truck.Add(new Web2.Job() { JobId = j.JobId, UserName = j.UserName, FirstName = "Job", LastName = "complete", SLat = j.SLat, SLon = j.SLon, ELat = j.ELat, ELon = j.ELon, Active = j.Active, Color = "table-warning" });
                                    a = false;
                                }
                            }
                            
                        }
                    }
                }
                if (a)
                {
                    if (j.Active)
                    {
                        truck.Add(new Web2.Job() { JobId = j.JobId, UserName = j.UserName, FirstName = "Needs", LastName = "Truck", SLat = j.SLat, SLon = j.SLon, ELat = j.ELat, ELon = j.ELon, Active = j.Active, Color = "table-danger" });
                    }
                    else
                    {
                        truck.Add(new Web2.Job() { JobId = j.JobId, UserName = j.UserName, FirstName = "Job", LastName = "complete", SLat = j.SLat, SLon = j.SLon, ELat = j.ELat, ELon = j.ELon, Active = j.Active, Color = "table-warning" });
                    }
                    
                }
            }
            return truck.ToJSON();
        }
        public string newJob(JobModel t)
        {
            var temp = t.UserName.ToString().Split(',');
            Job j = new Web2.Job();
            Info i = new Info();
            i.UserName = "No Driver";
            j.SLat = decimal.Parse(temp[0]);
            j.SLon = decimal.Parse(temp[1]);
            j.ELat = decimal.Parse(temp[2]);
            j.ELon = decimal.Parse(temp[3]);
            var pass = ch.newJob(j);
            return pass.ToString();
        }
        public string complete(JobModel j)
        {
            var a = j.UserName;
            Job i = new Job();
            i.JobId = int.Parse(a);
            ch.dectivateJob(i);
            return "true";
        }
        public string GetUserListInfo()
        {
            var users = ch.RetrieveInfo();
            List<Info> info = new List<Info>();
            foreach (var item in users)
            {
                info.Add(new Web2.Info() { UserName = item.UserName });
            }
            return info.ToJSON();
        }
        public string saveChange(TruckModel t)
        {
            var a = t.UserName.ToString().Split(',');
            Info i = new Info();
            Job j = new Web2.Job();
            i.UserName = a[1];
            j.JobId = int.Parse(a[0]);
            ch.addToJob(i, j);

            return "true";
        }
    }
}

FleetManagment/FleetManagement.Web2/Controllers/JobController.cs
using FleetManagement.Web2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FleetManagement.Web2.Controllers
{
    public class JobController : Controller
    {
        // GET: Job
        ClientHelper ch = new ClientHelper();
        public ActionResult Job()
        {
            var info = ch.RetrieveInfo();
            var job = ch.RetrieveJobs();
            var j = Session["UN"];
            var jobAvailable = false;
            foreach (var item in job)
            {
                if (item.UserName == j.ToString() && item.Active == true)
                {
                    Session["SLAT"] = item.SLat;
                    Session["SLON"] = item.SLon;
                    Session["ELAT"] = item.ELat;
                    Session["ELON"] = item.ELon;
                    jobAvailable = true;
                }
            }
            if (jobAvailable)
            {
                return View("CheckJob");
            }else
            {
                return View("NoJob");
            }
           
        }
        public ActionResult CheckIn()
        {
            var truck = ch.RetrieveTrucks();
            var isTruck = false;
            foreach (var item in truck)
            {
                if (item.UserName == Session["UN"].ToString())
                {
                    isTruck = true;
                }
            }
            if (isTruck)
            {
                return View("CheckIn");
            }else
            {
                return View("NoTruck");
            }
            
        }
        public string NewLoc(JobModel j)
        {
            var loc = j.UserName.ToString().Split(',');
            Truck l = new Truck();
            l.CLat = decimal.Parse(loc[0]);
            l.CLon = decimal.Parse(loc[1]);
            l.TruckNumber = int.Parse(Session["TN"].ToString());
            var res = ch.updateLocation(l);
            return res.ToString();


        }
        
    }
}

FleetManagment/FleetManagement.Web2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/style.css" />
    <link rel="stylesheet" href="~/Content/form-element.css" />
    <script src=https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js></script>
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
    <style>
        #map {
            width: 100%;
            height: 400px;
            background-color: grey;
        }
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fleet Management USA", "Home", "Home", new { area = "" }, new { @class = "navbar-brand", style = "padding-top:15px" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Current Job", "Job", "Job")</li>
                    <li>@Html.ActionLink("Check In", "CheckIn", "Job")</li>
                    <li>@Html.ActionLink("Logout", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding-top:41px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FleetManagment/FleetManagement.Web2/Views/Shared/_LayoutEmployee.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/style.css" />
    @*<link rel="stylesheet" href="~/Content/form-element.css" />*@
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fleet Management USA", "Home", "Home", new { area = "" }, new { @class = "navbar-brand", style="padding-top:15px"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Current Job", "Job", "Job")</li>
                    <li>@Html.ActionLink("Check In", "CheckIn", "Job")</li>
                    <li>@Html.ActionLink("Trucks", "Truck", "Truck")</li>
                    <li>@Html.ActionLink("Employees", "Employee", "User")</li>
                    <li>@Html.ActionLink("Jobs", "Job", "EJob")</li>
                    <li>@Html.ActionLink("Logout", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding-top:41px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FleetManagment/FleetManagement.Web2/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fleet Management USA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Sign-Up", "signup", "Home")</li>*@
                    <li>@Html.ActionLink("Login", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sign-Up", "Register", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fleet Management USA</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>